; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "docxearch"
#define MyAppVersion "3.2"
#define MyAppPublisher "Jung Il Oh"
#define MyAppExeName "docxearch.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{F58C4620-DF2C-481E-AF14-34F62C8B8647}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\woosu\Projects\Apps\doc search app\docxearch license.txt
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputBaseFilename=docxearch_setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\woosu\Projects\Apps\doc search app\dist\docxearch\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\woosu\Projects\Apps\doc search app\dist\docxearch\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Code]
var
  ApiKeyPage: TInputQueryWizardPage;

procedure InitializeWizard();
begin
  ApiKeyPage := CreateInputQueryPage(wpSelectDir,
    'OpenAI API Key', 'Enter your API key',
    'Please enter your OpenAI API key below. This will be used by the app to access OpenAI services.');
  ApiKeyPage.Add('API Key:', False);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  KeyFile: String;
  KeyText: String;
begin
  if CurStep = ssPostInstall then begin
    KeyFile := ExpandConstant('{app}\.env');
    KeyText := 'OPENAI_API_KEY=' + ApiKeyPage.Values[0];
    SaveStringToFile(KeyFile, KeyText, False);
  end;
end;

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

